### ISSUE TITLE
Prototype: Case and Task Management

### ISSUE THREAD

**Issue by majica** [majica/practice#3]
# Goal
Explore user interface and functional aspects of the user stories enumerated below. Use only simple declarative constructs and avoid Apex as much as possible
* #1 
* #4

# Tasks
- [ ] Case page layout
- [ ] Case Lightning record page
- [ ] Case-related Tasks, assignment, visibility and tracking from a case record
